[project]
org-name= "ballerinax"
version= "1.1.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["ballerina", "salesforce", "sfdc", "client", "connector"]
repository = "https://github.com/ballerina-platform/module-salesforce"
