[project]
org-name= "pramodya"
version= "0.1.0"
authors = ["Pramodya"]
keywords = ["ballerina", "salesforce", "sfdc", "client", "connector"]
repository = "https://github.com/wso2-ballerina/module-salesforce"
