# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the action will run.
# Triggers the workflow on release.
on:
  release:
    types:  [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build Ballerina Project
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@master
        with:
          args:
            pack ./salesforce
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          EP_URL: ${{ secrets.EP_URL }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          REFRESH_URL: ${{ secrets.REFRESH_URL }}
      # Push to Ballerina Central
      - name: Ballerina Push
        uses: ballerina-platform/ballerina-action/@master
        with:
          args:
            push
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          WORKING_DIR: ./salesforce
